apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: pacman-pipeline-run
spec:
  serviceAccountName: pipeline
  pipelineRef:
    name: pacman-pipeline
  resources:
    - name: pacman-git
      resourceRef:
        name: pacman-git
    - name: nodejs-image-dev
      resourceRef:
        name: pacman-image-dev
    - name: pacman-image-stage
      resourceRef:
        name: pacman-image-stage
  params:
    - name: DEPLOY_ENVIRONMENT
      value: 'env-dev'
    - name: PROMOTE_ENVIRONMENT
      value: 'env-stage'